프로세스 재시작 CD
teamdable/vv-deploy-actions pull request #12
Opened 2022-03-03 07:12 UTC by yunseung-dable

기존 restarter 커밋 정리하여 다시 올립니다

2022-03-03 07:19 UTC, hyeseung-of-dable requested changes

2022-03-03 07:19 UTC, hyeseung-of-dable commented on kill_process.exp
> +set parent_dir [lindex $argv 5]
parent-dir 변수는 사용안해서 삭제하셔도 될 듯 합니덩

2022-03-03 07:19 UTC, hyeseung-of-dable commented on restart_process_after_deploy.sh
> +  fi
kill_process, start_process에서 사용하는 `expect script`는 에러코드 관리가 안되어서, 실패해도 요 if문에는 안걸릴거에요.

저는 그래서 결과를 txt파일로 저장해서, 출력된 결과를 보고 판단하는 쉘 스크립트를 따로 작성했습니당ㅎㅎ ([예시](https://github.com/teamdable/vv-deploy-actions/blob/main/deploy-to-edge-devices.sh#L34-L37))

2022-03-03 07:19 UTC, hyeseung-of-dable commented on restart_process_after_deploy.sh
> +CODE_NAME=$5
배포쪽에서 사용하는 CODE_NAME 변수는 모듈 레포 이름(vv-yolor, edge-player, process, resource)입니당.

여기에서는 `start-*`에 사용되어야하니 inference, edge-player, process-monitoring, resource-monitoring 이 전달되어야해서, 변수명을 분리?변경?하는 등이 필요해보입니다 🙇

2022-03-07 08:46 UTC, yunseung-dable commented
[테스트성공 후 start_process.exp 에도 조건문 코드 동일하게 반영](https://github.com/teamdable/vv-deploy-actions/pull/12/commits/dae23838078b23ce8d9522ae18e702c131e3ff13)
커밋에서 exit-code를 받아와서 처리하도록 코드 수정했습니다! 
성공시 exit-code 0 그 외 실패시 1 or 127 등 의 코드를 통해 성공 실패를 확인하고 다음 스텝을 진행할 수 있습니다
[리소스모니터링 테스트 사례](https://github.com/teamdable/vv-resource-monitoring/runs/5444653968?check_suite_focus=true#step:8:72)

2022-03-07 09:17 UTC, hyeseung-of-dable commented
아! 버전만 업데이트 해주세요! @yunseung-dable

2022-03-07 09:21 UTC, yunseung-dable commented
> 아! 버전만 업데이트 해주세요! @yunseung-dable

[버전업 커밋](https://github.com/teamdable/vv-deploy-actions/pull/12/commits/b435e6110067f7641274ce334ce1f405330b7524) 외에 추가로 또 업해야할까요?

2022-03-07 09:21 UTC, yunseung-dable commented
> > 아! 버전만 업데이트 해주세요! @yunseung-dable
> 
> [버전업 커밋](https://github.com/teamdable/vv-deploy-actions/pull/12/commits/b435e6110067f7641274ce334ce1f405330b7524) 외에 추가로 또 업해야할까요?

@hyeseung-of-dable

2022-03-07 09:23 UTC, hyeseung-of-dable commented
@yunseung-dable 최신 디벨롭으로 rebase하시면 1.0.2a2 라서 아마 https://github.com/teamdable/vv-deploy-actions/pull/12/commits/b435e6110067f7641274ce334ce1f405330b7524 커밋에서 충돌날듯해요ㅎㅎ
1.0.2a3으로 버전업하시고, develop으로 머지해주시면 됩니당~~!!

2022-03-07 09:33 UTC, merged