새로운 워크플로우 구조생성
teamdable/vv-deploy-actions pull request #69
Opened 2022-04-21 07:30 UTC by yunseung-dable

1. 입력값으로 디바이스를 받아 처리한다
2. 한개의 job 안에 세부 step들을  각각의 job으로 분리하여 배포의 진행상황을 관리하기 용이하다
3. 워크플로우를 재조합하여 사용하기에 구조적으로 용이

2022-04-25 01:30 UTC, jingu-lee reviewed
작성 해놓은 내용들 중 윤승님 판단하기에 수정이 필요한 부분만 수정해서 다시 리퀘스트 주세요

2022-04-25 01:30 UTC, jingu-lee commented on .github/workflows/deploy-to-each-device.yml
> +        required: true
이건 얘기해볼 부분이긴 한데, self-hosted-runner로 배포를 하기로 했다면 굳이 각 레포에서 이 secrets를 관리하지 않아도 될 것 같습니다

2022-04-25 01:30 UTC, jingu-lee commented on deploy-file.sh
> +  --user)
indent가 다른 라인하고 다릅니다

2022-04-25 01:30 UTC, jingu-lee commented on deploy-file.sh
> +}
저희 대부분의 스크립트가 이렇게 작성되어 있기는 한데, 사실 인자 전달이 잘못되었으면 help를 띄워주는 것이 보편적인 듯 합니다. actions에서 다룬다고 할 지라도 인자가 하나가 아니기 때문에 ;잘못되었다' 보다는 현재 전달된 인자를 보여주는 방식도 좋아 보입니다.

2022-04-25 01:30 UTC, jingu-lee commented on deploy-to-each-device.sh
> +  --user)
이곳도 인덴트!

2022-04-25 08:39 UTC, yunseung-dable commented on .github/workflows/deploy-to-each-device.yml
> +        required: true
마자용, 그런데 secret을 organization 단위에서 설정하려다가 지금 흐지부지 된거 아닌가요?

2022-04-25 08:47 UTC, yunseung-dable commented on deploy-file.sh
> +  --user)
이게 ide 상으론 똑같은데 github에 올리면 다르게 나타날때가 종종 있더라구요!
PyCharm 만 그런줄 알았는데 vscode도 그렇다는걸 찾아서 나중에 비슷한 경험하실때 참고하시면 좋을것 같습니다
https://github.com/github/VisualStudio/issues/1524

2022-04-25 08:51 UTC, yunseung-dable commented on deploy-file.sh
> +}
진구님 친절한 개발자시군요

2022-04-28 00:05 UTC, jingu-lee commented on .github/workflows/deploy-to-each-device.yml
> +        required: true
organization 단위의 secrets는 self-hosted runner를 안 쓸 때 필요하고, self-hosted runner를 쓰면 내부적으로 secrets를 가지고 있을 수 있습니다.

2022-04-28 00:06 UTC, jingu-lee approved these changes
저는 큰 문제가 없어 보이긴 하는데, 제가 CD 구조를 몰라서 혜승님이나 다른 분들도 리뷰하신 후 머지하는 게 좋아보입니다.

2022-05-09 03:09 UTC, hyeseung-of-dable requested changes
deploy-to-each-device.sh 는 사용하지않는 것 같은데, 만드신 이유가 있을까요?!

2022-05-09 03:09 UTC, hyeseung-of-dable commented on .github/workflows/deploy-to-each-device.yml
> +        required: true
self-hosted runner에서 다른 장비들의 pwd를 관리하는게 보안상 좋지않아, 여전히 secrets를 사용하고있습니다

2022-05-10 05:47 UTC, yunseung-dable commented
리뷰코드 반영 하려고 보니 몇가지 추가 되었으면 하는 기능이 생각나서 공유드립니다.
1. vpn.ini 파일 대신 입력으로 받으며 live 장비 전체배포 기능이 사라져서 이번 merge 이후에 추가하면 좋을것 같습니다! 
2. github actions outputs 기능을 활용하여 version check, install-check 부분을 간소화할 수 있을것 같습니다!

2022-05-11 00:33 UTC, hyeseung-of-dable requested changes
@yunseung-dable 

1. https://github.com/teamdable/vv-deploy-actions/issues/22 요 이슈를 어느정도해결해주셨더라구요 ㅎㅎ live 포함하는 부분은, 이슈 댓글처럼 get-vpn-ip쪽에서 수정 + 배포할 때, 레포에서 사용자가 live포함할지안할지 t/f입력하도록 수정할 예정입니다!
2. 좋씁니다 !! 그러면 expect때문에 불안한것도 어느정도 해소되겠네요!

2022-05-11 00:33 UTC, hyeseung-of-dable commented on README.md
> +          process-name: 'resource-monitoring'
퍼블릭이라 계정명등을 올리지않고있습니다~~
reset 했다가 커밋다시올려주세요!

기존 예시)
```
uses: teamdable/vv-deploy-actions/.github/workflows/deploy-to-edge-devices.yml@main
with:
    user: 'ubuntu'
!   code-name: 'inference'
!   deploy-branch: ${GITHUB_REF##*/} 
!   parent-dir: '/home/ubuntu/'
!   version-file-name: '_version.py'
-   exclude-files-from-zip: 'bin/deploy/vpn-config.ini'
+   
!   slack-channel: 'general'
```

2022-05-11 08:51 UTC, hyeseung-of-dable approved these changes

2022-05-11 08:51 UTC, hyeseung-of-dable commented
수고하셨습니다 ~~🚀🚀🚀

2022-05-11 13:38 UTC, merged