version, install check 리팩토링
teamdable/vv-deploy-actions pull request #79
Opened 2022-05-18 03:41 UTC by yunseung-dable

[정리 슬랙](https://dable.slack.com/archives/C01163RRG8M/p1652413854394659)

2022-05-19 01:06 UTC, hyeseung-of-dable requested changes
이번 branch가 머지되면 기존 배포는 동작을 안하게될 것 같아요. 
순차적으로 deprecated되는 것이 목표라서, 기존 코드들은 두고 새로 파일을 생성하는 게 좋을 듯 합니다ㅎㅎ

점점 배포파일이 많아지니, v1.2.0버전대의 파일들을 이제 디렉토리를 두고 관리해도 괜찮겠네요!
deploy/
install/
restart/ 등등..!

2022-05-19 01:06 UTC, hyeseung-of-dable commented on .github/workflows/parallel_deployment.yml
> +          action/compare-raw-versions.sh --version-file ${{ inputs.version-file-name }} --source-version-raw "$source_version_raw" --target-version-raw "$target_version_raw"
python _version.py와 .version 파일에서만 동작하고, edge-player의 packages.json에서는 동작을 안합니다! 

그래서 기존에 이런 복잡한 작업이 있었습니다ㅠ
https://github.com/teamdable/vv-deploy-actions/blob/f14ec6b0a1091553211fab3c2f501dc6eb2c7e71/install-check.sh#L41-L52

2022-05-19 01:16 UTC, yunseung-dable commented
> 이번 branch가 머지되면 기존 배포는 동작을 안하게될 것 같아요. 순차적으로 deprecated되는 것이 목표라서, 기존 코드들은 두고 새로 파일을 생성하는 게 좋을 듯 합니다ㅎㅎ
> 
> 점점 배포파일이 많아지니, v1.2.0버전대의 파일들을 이제 디렉토리를 두고 관리해도 괜찮겠네요! deploy/ install/ restart/ 등등..!

기존 파일들은 내용을 변경하거나 지우지 않고 둬야겠네요!

2022-05-19 01:24 UTC, yunseung-dable commented on .github/workflows/parallel_deployment.yml
> +          target_version_split=(${target_version_raw})
> @yunseung-dable
> 
> L132: target_version_split에 assign한 후에 L133: space로 구분해서 맨 뒤에거 가져온다 고 이해했어요. 제가 잘못 이해한 부분이 있을까요 ??~
> 
> 저는 `target_version_split=(${target_version_raw})` 로 하니까, 의도치않은 결과가 나왔습니다!

기존 $target_version_raw 는 expect의 결과가 담겨있는 string 파일입니다.
L132는 이 스트링을 space 기준으로 split 한 array를 갖게 되구요. 
L133은 array에서 맨마지막 실제버전숫자를 가져오려는 의도였습니다!

[이게](https://github.com/teamdable/vv-resource-monitoring/runs/6483358675?check_suite_focus=true#step:5:11) 제가 테스트로 실행시킨 결과인데 source version, target version 원하는 결과가 나와서요~ 혹시 혜승님 결과 링크를 볼 수 있을까요?

2022-05-23 08:23 UTC, yunseung-dable commented on .github/workflows/deployment-with-restart.yml
> +          sleep 10
네 맞습니다
정말 넣기 싫었는데 race condition 때문인지 expect 스크립트를 사용하는 스텝이 4개이상되면 그때부터 버그가 발생하더라구요
(잘되던 expect 스크립트에서 비밀번호를 계속 틀린다던지) 그래서 불가피하게 스텝간에 sleep 10초씩 사용했어요

2022-05-23 08:24 UTC, hyeseung-of-dable commented on .github/workflows/deployment-with-restart.yml
> +          sleep 10
ㅋㅋㅋㅋㅋ 쉘파일로 감싸도 저렇게 되는군요 !! 넵넵 감사합니다 🙇

2022-05-23 08:49 UTC, hyeseung-of-dable commented on .github/workflows/deployment-with-restart.yml
> +          result=$(slackboy -m "${{ inputs.process-name }} 배포가 시작됩니다. 해당기기의 접속을 멈춰주세요.\nDevices : ${{ inputs.deploy-target-device }}" -p deploy-process -c "${{ inputs.slack-channel }}")
이전에 테스트했을 때, 뉴라인(\n) 적용이 안되었었던 기억이 있어서 확인해봤는데요!
https://dable.slack.com/archives/C02LKJ5HNTX/p1653295134241389 이렇게 됩니다...! 

그래서 [메세지를 따로 변수에 저장](https://github.com/teamdable/vv-deploy-actions/blob/f14ec6b0a1091553211fab3c2f501dc6eb2c7e71/deploy-to-edge-devices.sh#L75-L78)했었습니다 !!

2022-05-23 09:51 UTC, hyeseung-of-dable approved these changes

2022-05-24 02:17 UTC, merged