배포 완료/실패 기기 알려주기
teamdable/vv-deploy-actions pull request #93
Opened 2022-06-15 09:27 UTC by yunseung-dable

2022-06-21 08:18 UTC, hyeseung-of-dable approved these changes

2022-06-21 08:18 UTC, hyeseung-of-dable commented on get-device-id
> +def main(vpn_ip: str):
함수이름을 Get_device_id 등으로 명시하면 어떨까용~~??

2022-06-21 08:18 UTC, hyeseung-of-dable commented on .github/workflows/deployment-with-restart.yml
> +          echo "${{ matrix.vpn_ips }} Deployment Finish!!! :rocket:" >> $GITHUB_STEP_SUMMARY
이거 어떻게 나오는지 궁금한데, 혹시 테스트하신쪽 링크가 있을까요???

2022-06-21 08:18 UTC, hyeseung-of-dable commented on .github/workflows/deployment-with-restart.yml
> +    needs: [ Deployment-to-each-device ]
Deployment-to-each-device 잡이 실패해도, summary를 보내주면 좋을 것 같아요!!

2022-06-21 08:19 UTC, hyeseung-of-dable reviewed
잘못눌러서...re-request 셀프로날렸습니다ㅋㅋㅋㅋ

2022-06-21 08:33 UTC, hyeseung-of-dable commented
@yunseung-dable 

윤승님, 저희 내일 장비 조립하고 하면 코드 볼 시간이 없을 것 같은데,,,
현재 디벨롭 브랜치 먼저 머지하고, 요 PR은 다음 develop 버전으로 넘기면 어떨까요??

2022-06-21 08:35 UTC, yunseung-dable commented
> @yunseung-dable
> 
> 윤승님, 저희 내일 장비 조립하고 하면 코드 볼 시간이 없을 것 같은데,,, 현재 디벨롭 브랜치 먼저 머지하고, 요 PR은 다음 develop 버전으로 넘기면 어떨까요??

네 그게 좋을것 같습니다!

2022-06-27 01:38 UTC, yunseung-dable commented on .github/workflows/deployment-with-restart.yml
> +          echo "${{ matrix.vpn_ips }} Deployment Finish!!! :rocket:" >> $GITHUB_STEP_SUMMARY
테스트링크입니다!
https://github.com/teamdable/vv-resource-monitoring/actions/runs/2501113718/attempts/1#summary-6896680367

2022-06-28 02:06 UTC, yunseung-dable commented on .github/workflows/deployment-with-restart.yml
> +    needs: [ Deployment-to-each-device ]
넵 아래는  예시 입니다
[그래프 예시](https://github.com/teamdable/vv-resource-monitoring/actions/runs/2573261884)
[슬랙예시](https://dable.slack.com/archives/C02LKJ5HNTX/p1656381632875899)

2022-06-30 08:15 UTC, hyeseung-of-dable requested changes

2022-06-30 08:15 UTC, hyeseung-of-dable commented on .github/workflows/deployment-with-restart.yml
> +          echo "${{ matrix.vpn_ips }} Deployment Finish!!! :rocket:" >> $GITHUB_STEP_SUMMARY
get-device-id도 만들어주셨으니, `get-device-id --vpn-ip ${{ matrix.vpn_ips }}` 결과로 하면 어떨까요?!!

2022-06-30 08:15 UTC, hyeseung-of-dable commented on get-device-id
> +def main(vpn_ip: str):
윤승님 get-vpn-ip-new 함수이름이 get_device_id로 바뀌었습니다 ㅎㅎ

2022-07-01 02:58 UTC, hyeseung-of-dable approved these changes
수고하셨습니다 !!!!!! 🚀🚀🚀

2022-07-01 03:10 UTC, yunseung-dable commented
> get-device-id도 만들어주셨으니, get-device-id --vpn-ip ${{ matrix.vpn_ips }} 결과로 하면 어떨까요?!!

이거 열심히 수정했는데 request 주셨다가 왜째서 다시 approval 하신건가요! ㅋㅋㅋㅋ
https://github.com/teamdable/vv-resource-monitoring/actions/runs/2593994197

2022-07-01 03:12 UTC, hyeseung-of-dable approved these changes
b5aa0dd73b1d35fec11b5c48d0a593937995f9a5 요 커밋 확인하고 appprove 했어요ㅎㅎㅎ 👍👍

2022-07-01 03:15 UTC, merged